CREATE TABLE import_batch (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name       VARCHAR(255) NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    total_rows        INT NOT NULL DEFAULT 0,
    empty_rows        INT NOT NULL DEFAULT 0,
    new_leads         INT NOT NULL DEFAULT 0,
    duplicates_merged INT NOT NULL DEFAULT 0,
    to_process        INT NOT NULL DEFAULT 0,
    processed         INT NOT NULL DEFAULT 0,
    unmapped_columns  VARCHAR(1000),
    error             VARCHAR(1000),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at       TIMESTAMP WITH TIME ZONE
);

CREATE TABLE lead (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT,
    company          VARCHAR(255) NOT NULL,
    company_key      VARCHAR(255) NOT NULL,
    domain           VARCHAR(255),
    website          VARCHAR(500),
    industry         VARCHAR(255),
    city             VARCHAR(120),
    state            VARCHAR(120),
    country          VARCHAR(120),
    employees        INT,
    revenue_usd      BIGINT,
    founded_year     INT,
    owner_name       VARCHAR(255),
    owner_title      VARCHAR(255),
    email            VARCHAR(255),
    email_status     VARCHAR(20) NOT NULL,
    phone            VARCHAR(40),
    phone_valid      BOOLEAN NOT NULL DEFAULT FALSE,
    linkedin_url     VARCHAR(500),
    website_status   VARCHAR(20) NOT NULL,
    website_note     VARCHAR(255),
    description      VARCHAR(2000),
    signals          VARCHAR(8000),
    enriched_fields  VARCHAR(500),
    source_rows      INT NOT NULL DEFAULT 1,
    score            INT NOT NULL DEFAULT 0,
    tier             VARCHAR(2) NOT NULL DEFAULT 'C',
    score_breakdown  VARCHAR(8000),
    excluded_reason  VARCHAR(255),
    status           VARCHAR(20) NOT NULL,
    notes            VARCHAR(4000),
    ai_brief         VARCHAR(8000),
    ai_provider      VARCHAR(40),
    processing       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    version          BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_lead_domain ON lead (domain);
CREATE INDEX idx_lead_company_key ON lead (company_key);
CREATE INDEX idx_lead_tier_score ON lead (tier, score);
CREATE INDEX idx_lead_status ON lead (status);

CREATE TABLE app_setting (
    setting_key   VARCHAR(80) PRIMARY KEY,
    setting_value VARCHAR(8000) NOT NULL
);
